config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  captcha_route
  root 'torre_travels#index'
  resources :slyders, only: [:all]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :index]
  resources :torre_travels, only:[:show]
  get 'service',     to: 'torre_travels#service'
  get 'sights',      to: 'slyders#all'
  get 'all_types',   to: 'torre_travels#all_housings'
  get 'housing',     to: 'torre_travels#housing'
  match '/signin',   to: 'sessions#new',         via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
end

app/models/comment.rb
# class Comment
class Comment < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :name, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { in: 1..160 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
end

app/models/commercial.rb
class Commercial < ActiveRecord::Base
end

app/models/image.rb
# class image
class Image < ActiveRecord::Base
  belongs_to :torre_travel
  has_attached_file :image_of_housing, :styles => { :large =>'800x600!', :medium => '300x300>', :small => '256x192!' }
  validates_attachment_content_type :image_of_housing, :content_type => /\Aimage\/.*\Z/
end

app/models/slyder.rb
# class slyder
class Slyder < ActiveRecord::Base
  has_attached_file :poster, :styles => { large:'1280x360!', small:'512x144!'}
  validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/
end

app/models/torre_travel.rb
# class of the housing
class TorreTravel < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  has_many :images, dependent: :destroy

  after_create  :create_tt
  after_update  :update_tt
  after_destroy :destroy_tt

  enum housing: [:house, :flat, :bungalo, :chelet]
  enum distance: [:first_line, :second_line]
  enum reserved: [:reserv, :unreserv]

  validates :description, presence: true, length: { minimum: 5 }
  validates :description_es, presence: true, length: { minimum: 5 }
  validates :price, presence: true
  validates :housing, presence: true

  def self.restricted_statuses
    statuses.except :failed, :destroyed
  end

  def create_tt
    AdminMailer.new_housing(self).deliver_now
  end

  def update_tt
    AdminMailer.edit_housing(self).deliver_now
  end

  def destroy_tt
    AdminMailer.torre_travel_destroyed(self).deliver_now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :login, presence: true
    validates :password, presence: true
    has_secure_password
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # reset captcha code after each request for security
  after_filter :reset_last_captcha_code!
  before_action :commercials
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def commercials
    @commercials = Commercial.all
  end
end

app/controllers/comments_controller.rb
# comments_controller
class CommentsController < ApplicationController
  before_action :all_comments, only: [:create, :index]
  def create
    @comment = Comment.new(comments_params)
    if valid_captcha?(params[:captcha])
      if @comment.save
        redirect_to comments_path, notice: "Отзыв был успешно добавлен!"
        AdminMailer.new_comment(@comment).deliver_now
      else
        flash.now[:notice] = "Возникли ошибки, попробуйте еще раз!"
        render 'index'
      end
    else
      flash[:notice] = "Не правильно введен код с картинки!"
      render 'index'
    end
  end

  def index
    @comment = Comment.new
  end

  private

  def all_comments
    @comments = Comment.paginate(page: params[:page], per_page: 6)
  end

  def comments_params
    params.require(:comment).permit(:name, :body, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(login: params[:session][:login].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to rails_admin_path # поменять на страницу админа
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/slyders_controller.rb
class SlydersController < ApplicationController   
  def all
    @slyders = Slyder.all
  end
end

app/controllers/torre_travels_controller.rb
# clss Torre travel
class TorreTravelsController < ApplicationController
  before_action :set_torre_travel, only: [:show]
  before_action :all_torre_travels, only: [:index, :all_housings]

  def index
    @slyders = Slyder.all
  end

  def housing
    @torre_travels = TorreTravel.paginate(page: params[:page], per_page: 4).where(housing: params[:housing])
  end

  def service
  end

private

  def all_torre_travels
    @torre_travels = TorreTravel.paginate(page: params[:page], per_page: 4)
  end

  def set_torre_travel
    @torre_travel = TorreTravel.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commercials_helper.rb
module CommercialsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/torre_travels_helper.rb
module TorreTravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="new_comment">
<%if notice%>
  <p id="notice"><%= notice %></p>
<% end %>
<a href="#?w=500" rel="popup_name" class="poplight">Оставить отзыв</a>
  <div id="popup_name" class="popup_block">
    <h3>Написать отзыв:</h3>
    <%= form_for(@comment) do |f| %>
    <%= f.error_messages :header_message => "Ошибка заполнения формы",
  :message => "Вы должны исправить эти ошибки:",
  :header_tag => :h3%>
      <div class="field">
        <%=f.text_area :name, placeholder: "Ваше имя..."%>
      </div>
      <div class="field">
        <%=f.email_field :email, placeholder: "Ваш email..."%>
      </div>
      <div class="field">
        <%= f.text_area :body, placeholder: "Отзыв...", rows: 4 %>
      </div>
      <div class="emojis">
        <%=raw ':thumbsup:'.emojify%>
        <%=raw ':thumbsdown:'.emojify%>
        <%=raw ':ok_hand:'.emojify%>
        <%=raw ':v:'.emojify%>
        <%=raw ':clap:'.emojify%>
        <%=raw ':smile:'.emojify%>
        <%=raw ':relaxed:'.emojify%>
        <%=raw ':heart_eyes:'.emojify%>
        <%=raw ':weary:'.emojify%>
        <%=raw ':sob:'.emojify%>
        <%=raw ':rage:'.emojify%>
        <%=raw ':sunglasses:'.emojify%>
        <%=raw ':smiling_imp:'.emojify%>
        <%=raw ':sunny:'.emojify%>
        <%=raw ':umbrella:'.emojify%>
        <%=raw ':cloud:'.emojify%>
        <%=raw ':ocean:'.emojify%>
        <%=raw ':foggy:'.emojify%>
      </div><br>
      <center><div class="field"><%= captcha_tag %></div></center>
      <div class="field"><%= text_field_tag :captcha %></div>
      <div class="field">
      <%= f.submit "Написать" %>
      </div>
    <% end %>
  </div>   
</div>
<div class="new">
  <h2>Отзывы</h2>
    <% @comments.each do |comment| %>
      <li>
        <div class="title_com">
          <%= comment.name%><br>
          <span class="timestamp">
            <%= (comment.created_at) %>
          </span>
        </div>
      </li>
      <div class="body_com">
        <%= raw render_emoji(comment.body, { :style => 'width:20px;' }) %>
      </div>
      <%end%>
      <div class="apple_pagination">
        <%= will_paginate %>
      </div>
  </div> 
</div>

app/views/commercials/_index.html.erb
<%= commercial.phone %>
<%= commercial.address%>
<%= mail_to "#{commercial.email}",commercial.email,{:style=>'color:inherit; font-size:inherit; text-transform:lowercase'} %>
<%= commercial.body %>

app/views/image/edit.html.erb
<h1>Edit image:</h1>
<%= form_for([@torre_travel, @image]) do |f| %>
<%= render partial: "form", locals:{ f: f} %>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <title>Torre-Travels</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if signed_in? %>
      <%=render "partials/panel"%>      
    <%end%>
    <%=render "partials/header"%>
    <div class="content">
      <%= yield %>
    </div>
    <%=render "partials/footer"%>
    <div class="admin link">
      <% unless signed_in? %>
          <%= link_to "Sign in", signin_path %>
      <%end%>
    </div>
  </body>
</html>

app/views/partials/_center.html.erb
<ul>
  <center>
  <h2>Жилье в наличии:</h2>
  <%= link_to 'Апартаменты', housing_path(housing: "0")%><br>
  <%= link_to 'Квартиры', housing_path(housing: "1") %><br>
  <%= link_to 'Бунгало', housing_path(housing: "2") %><br>
  <%= link_to 'Челеты', housing_path(housing: "3") %><br>
  </center>
</ul>

app/views/partials/_footer.html.erb
<div class="jp-title">
  <ul>
    <li class="scrollingtext">
      <% @commercials.each do |commercial|%>
        <%= render partial:"commercials/index", locals:{commercial: commercial }%>
      <%end%> 
    </li>
  </ul>
</div>

app/views/partials/_header.html.erb
<div id="header">        
  <ul>
    <li><%= link_to 'Главная страница', :root %></li>
    <li><%= link_to 'Интересные места', sights_path %></li>
    <li><%= link_to 'Просмотреть все', all_types_path %></li>
    <li><%= link_to 'Отзывы', comments_path %></li>
  </ul>
</div>

app/views/partials/_image.html.erb
<div class="col-md-1">
  <%= link_to 'Назад', all_types_path %>
</div>
<div class="col-md-8">
  <%if @torre_travel.images.any?%>
    <div class="frame">
      <div class="fotorama" data-width="768" data-height="576" data-loop="true" data-autoplay="3000">
        <% @torre_travel.images.each do |image|%>
          <%= image_tag image.image_of_housing.url(:large) %>
        <%end%>
      </div>
    </div>  
  <%else%>
     <%=image_tag("large/missing2.png")%>
  <%end%> 
  
  <div id="popup_name" class="popup_block">
    <%=render partial:"partials/left"%>
  </div> 
</div> 

app/views/partials/_index.html.erb
<%if @torre_travels.any?%>
<div id="wrapper">
  <div id="contentArea">
    <div id="primaryContent">
    <% @torre_travels.each do |torre_travel| %>
      <div class="portfolioBox">
        <%if torre_travel.reserved == "reserv"%>
          <div class="reserved" VALUE="<%=torre_travel.id%>"></div>
        <%end%>
      <%if torre_travel.images.any?%>
        <%=link_to (image_tag torre_travel.images.first.image_of_housing.url(:small)), torre_travel%>  
      <%else%>
      <%=link_to (image_tag("small/missing2.png")), torre_travel%>
      <%end%>
        <h3>
          <%if torre_travel.housing == "house" %>
            <%= "Апартаменты" %> ID<%=torre_travel.id%>
          <%elsif torre_travel.housing == "flat"%>
            <%= "Квартира"%> ID<%=torre_travel.id%>
          <%elsif torre_travel.housing == "bungalo"%>
            <%= "Бунгало"%> ID<%=torre_travel.id%>
          <%else%>
            <%= "Челет"%> ID<%=torre_travel.id%>
          <%end%>
        </h3>
        <%= torre_travel.price %> €
        <%if torre_travel.housing == "flat" %>
          <%if torre_travel.distance == "first_line" %>
            <div class="line">
              <p title="менее 1000м до моря" style="cursor:help;"><%= "1ая линия" %></p> 
            </div>
          <%else%>
            <div class="line">
              <p title="более 1000м до моря" style="cursor:help;"><%= " 2ая линия"%></p>
            </div>
          <%end%>
        <%else%>
          <p>До моря 
            <%= torre_travel.distance_m %> м
          </p>
        <%end%>
      </div>     
      <%end%>
        <div class="apple_pagination">
           <%= will_paginate %>
        </div>          
    </div>
    <div id="secondaryContent">
    <%= render partial: "partials/service" %>
    </div>
  </div>
  <br> 
</div>
<%else%>
  <h1>Извините, такого жилья временно нет в наличии!</h1>
<%end%>

app/views/partials/_left.html.erb
<div class="left">
  <center>
  <h2>Cвяжитесь с нами :</h2>
    <p id="top-left">
      +34 602 416 651 Торревъеха Испания<br>
      torretravel2015@gmail.com
      <div class="email_us"><%= mail_to "torretravel2015@gmail.com", "Написать нам"%></div><br>
    </p>
  </center>
</div>

app/views/partials/_panel.html.erb
<div class="panel">
  <ul>
    <li><%= link_to "Админка", rails_admin.dashboard_path%></li>
    <li><%= link_to "Выйти из админки", signout_path, method: "delete" %></li>
  </ul>
</div>

app/views/partials/_right.html.erb
<div class="right">
  <div class="service">
  <center>
    <h2>Наши услуги :</h2>
    
      <p id="top-right">
         <%= link_to 'Гид по городу', service_path%><br>
         <%= link_to 'Экскурсовод', service_path%><br>
         <%= link_to 'Проезд', service_path%><br>
      </p>
      </center>
  </div>
</div>

app/views/partials/_service.html.erb
<div class="service_page">
<center><h2>Наши услуги</h2></center>
<h3>Переводчик</h3>
<p>
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>
<h3>Проводник</h3>
<p>
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
</p>
<h3>Встретим</h3>
<p>
There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
</p>
</div>

app/views/partials/_top.html.erb
<div class="top">
  <h1>Торревьеха</h1>
  <p id="top-text">
    Город и муниципалитет в Испании, входит в провинцию Аликанте в составе автономного сообщества Валенсия (автономное сообщество). Муниципалитет находится в составе района (комарки) Вега-Баха-дель-Сегура. Занимает площадь 71,44 км². Население города в начале 2008 года составило 100 000 человек — из которых 46,4 % — испанцы, 53,6 % — иностранцы, среди которых большинство англичан, немцев и скандинавов. По численности населения — третий город в провинции после Аликанте и Эльче.     
  </p>
</div>

app/views/slyders/all.html.erb
 <div class="edit">
 <%if notice%>
      <p id="notice"><%= notice %></p>
    <% end %>
  <% @slyders.each do |slyder|%>
    <div class="row">
      <div class="col-md-6">
        <%= image_tag slyder.poster.url(:small) %><br><br><br><br>
      </div>
      <div class="col-md-6 ">
        <p>
          <%= slyder.description%><br><br><br>
        </p>
      </div>
    </div>
  <%end%>
</div>

app/views/torre_travels/all_housings.html.erb
    <%if notice%>
      <p id="notice"><%= notice %></p>
    <% end %>
    <div id="main-index">
      <%= render 'partials/index'%>
    </div>

app/views/torre_travels/housing.html.erb
<div class="index">
    <%if notice%>
      <p id="notice"><%= notice %></p>
    <% end %>
    <div id="main-index">
      <%= render 'partials/index'%>
    </div>
</div>

app/views/torre_travels/index.html.erb
<%if notice%>
  <p id="notice"><%= notice %></p>
<% end %>
<div class="fotorama" data-width="100%" data-height="360" data-loop="true" data-autoplay="5000" data-transition="crossfade">
  <% @slyders.each do |slyder|%>
    <%= image_tag slyder.poster.url(:large) %>
  <%end%> 
</div>
<div class="bg">
</div>
<div id="top">
  <%= render 'partials/top'%>
</div>
<div class="left-col">
  <%= render 'partials/left'%>
</div>
<div class="center-col">
  <%= render 'partials/center'%>
</div>
<div class="right-col">
  <%= render 'partials/right'%>
</div>

app/views/torre_travels/service.html.erb
<%= render partial: "partials/service" %>

app/views/torre_travels/show.html.erb
<div class="show">
    <%if notice%>
      <p id="notice"><%= notice %></p>
    <% end %>
<div class="row1">
  <%= render partial: "partials/image" %>
    <div class="description">
      <%if @torre_travel.reserved == "reserv"%>
        <div class="reserved"></div>
      <%end%>       
      <p style='font-style:italic;font-size: 27px;margin-top:10px;'>
        <strong> ID<%=@torre_travel.id%></strong>
      </p>
      <p>
        <strong>Тип жилья: </strong>
        <%if @torre_travel.housing == "house" %>
          <%= "Апартаменты" %>
        <%elsif @torre_travel.housing == "flat"%>
          <%= "Квартира"%>
        <%elsif @torre_travel.housing == "bungalo"%>
          <%= "Бунгало"%>
        <%else%>
          <%= "Челет"%>
        <%end%>
      </p>
      <p>
        <strong>Цена жилья: </strong>
        <%= @torre_travel.price %> €
      </p>

      <%if @torre_travel.housing == "flat" %>
        <p>
        <strong>Расстояние до моря: </strong>
        <%if @torre_travel.distance == "first_line" %>
          <%= "1ая линия" %>
        <%else%>
          <%= " 2ая линия"%>
        <%end%>
      </p>
      <%else%>
        <p>
        <strong>Расстояние до моря: </strong>
        <%= @torre_travel.distance_m %> м
      </p>
      <%end%>
      <p>
        <strong>Описание на рус: </strong>
        <%= @torre_travel.description %>
      </p>
       <p>
        <strong>Описание на исп: </strong>
        <%= @torre_travel.description_es %>
      </p>
      <p>
        <strong>Адресс: </strong>
        <%= @torre_travel.address %>
      </p>
        <center>
         <a href="#?w=500" rel="popup_name" class="poplight" style="margin-bottom:20px;">Зарезервировать</a>
        </center>
    </div>
  </div>
  

  <div class="share">
    <center>
      <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
      <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
      <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,viber" data-counter="" data-copy="first" data-description="Лучший сайт для поиска жилья в Испании"></div>
    </center>
  </div>
</div>